<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	
	<form action="" method="post">
		<table>
			<tr>
				<th>Name</th>
				<td><input name="nm" id="nm" type="text" /></td>
				<td><input type="submit" name="Submit" value="Submit" /></td>
			</tr>
		</table>

	</form>

</body>
</html>

<?php

if(isset($_POST['Submit']))
{
	$name = $_POST['nm'];
	$requestXML = '<?xml version="1.0"?>
	<ENVELOPE>
	<HEADER>
	<TALLYREQUEST>Import Data</TALLYREQUEST>
	</HEADER>
	<BODY>
	<IMPORTDATA>
	<REQUESTDESC>
	<REPORTNAME>Vouchers</REPORTNAME>
	<STATICVARIABLES>
	<SVCURRENTCOMPANY>Logimetrix Techsolutions Private Limited</SVCURRENTCOMPANY>
	</STATICVARIABLES>
	</REQUESTDESC>
	<REQUESTDATA>
	
	<TALLYMESSAGE xmlns:UDF="TallyUDF">
	<VOUCHER REMOTEID="" VCHKEY="" VCHTYPE="Sales" ACTION="Create" OBJVIEW="Invoice Voucher View">
	<OLDAUDITENTRYIDS.LIST TYPE="Number">
	<OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
	</OLDAUDITENTRYIDS.LIST>
	<DATE>20190401</DATE>
	<GUID></GUID>
	<NARRATION>DAP sale</NARRATION>
	<COUNTRYOFRESIDENCE>India</COUNTRYOFRESIDENCE>
	<PARTYNAME>Piyush Rai</PARTYNAME>
	<VOUCHERTYPENAME>Sales</VOUCHERTYPENAME>
	<REFERENCE>1</REFERENCE>
	<VOUCHERNUMBER>3</VOUCHERNUMBER>
	<PARTYLEDGERNAME>Piyush Rai</PARTYLEDGERNAME>
	<BASICBASEPARTYNAME>Piyush Rai</BASICBASEPARTYNAME>
	<CSTFORMISSUETYPE/>
	<CSTFORMRECVTYPE/>
	<FBTPAYMENTTYPE>Default</FBTPAYMENTTYPE>
	<PERSISTEDVIEW>Invoice Voucher View</PERSISTEDVIEW>
	<BASICBUYERNAME>Piyush Rai</BASICBUYERNAME>
	<BASICDATETIMEOFINVOICE>1-Jul-2019 at 15:54</BASICDATETIMEOFINVOICE>
	<BASICDATETIMEOFREMOVAL>1-Jul-2019 at 15:54</BASICDATETIMEOFREMOVAL>
	<VCHGSTCLASS/>
	<DIFFACTUALQTY>No</DIFFACTUALQTY>
	<ISMSTFROMSYNC>No</ISMSTFROMSYNC>
	<ASORIGINAL>No</ASORIGINAL>
	<AUDITED>No</AUDITED>
	<FORJOBCOSTING>No</FORJOBCOSTING>
	<ISOPTIONAL>No</ISOPTIONAL>
	<EFFECTIVEDATE>20190701</EFFECTIVEDATE>
	<USEFOREXCISE>No</USEFOREXCISE>
	<ISFORJOBWORKIN>No</ISFORJOBWORKIN>
	<ALLOWCONSUMPTION>No</ALLOWCONSUMPTION>
	<USEFORINTEREST>No</USEFORINTEREST>
	<USEFORGAINLOSS>No</USEFORGAINLOSS>
	<USEFORGODOWNTRANSFER>No</USEFORGODOWNTRANSFER>
	<USEFORCOMPOUND>No</USEFORCOMPOUND>
	<USEFORSERVICETAX>No</USEFORSERVICETAX>
	<ISEXCISEVOUCHER>No</ISEXCISEVOUCHER>
	<EXCISETAXOVERRIDE>No</EXCISETAXOVERRIDE>
	<USEFORTAXUNITTRANSFER>No</USEFORTAXUNITTRANSFER>
	<IGNOREPOSVALIDATION>No</IGNOREPOSVALIDATION>
	<EXCISEOPENING>No</EXCISEOPENING>
	<USEFORFINALPRODUCTION>No</USEFORFINALPRODUCTION>
	<ISTDSOVERRIDDEN>No</ISTDSOVERRIDDEN>
	<ISTCSOVERRIDDEN>No</ISTCSOVERRIDDEN>
	<ISTDSTCSCASHVCH>No</ISTDSTCSCASHVCH>
	<INCLUDEADVPYMTVCH>No</INCLUDEADVPYMTVCH>
	<ISSUBWORKSCONTRACT>No</ISSUBWORKSCONTRACT>
	<ISVATOVERRIDDEN>No</ISVATOVERRIDDEN>
	<IGNOREORIGVCHDATE>No</IGNOREORIGVCHDATE>
	<ISVATPAIDATCUSTOMS>No</ISVATPAIDATCUSTOMS>
	<ISDECLAREDTOCUSTOMS>No</ISDECLAREDTOCUSTOMS>
	<ISSERVICETAXOVERRIDDEN>No</ISSERVICETAXOVERRIDDEN>
	<ISISDVOUCHER>No</ISISDVOUCHER>
	<ISEXCISEOVERRIDDEN>No</ISEXCISEOVERRIDDEN>
	<ISEXCISESUPPLYVCH>No</ISEXCISESUPPLYVCH>
	<ISGSTOVERRIDDEN>No</ISGSTOVERRIDDEN>
	<GSTNOTEXPORTED>No</GSTNOTEXPORTED>
	<IGNOREGSTINVALIDATION>No</IGNOREGSTINVALIDATION>
	<ISVATPRINCIPALACCOUNT>No</ISVATPRINCIPALACCOUNT>
	<ISBOENOTAPPLICABLE>No</ISBOENOTAPPLICABLE>
	<ISSHIPPINGWITHINSTATE>No</ISSHIPPINGWITHINSTATE>
	<ISOVERSEASTOURISTTRANS>No</ISOVERSEASTOURISTTRANS>
	<ISDESIGNATEDZONEPARTY>No</ISDESIGNATEDZONEPARTY>
	<ISCANCELLED>No</ISCANCELLED>
	<HASCASHFLOW>No</HASCASHFLOW>
	<ISPOSTDATED>No</ISPOSTDATED>
	<USETRACKINGNUMBER>No</USETRACKINGNUMBER>
	<ISINVOICE>Yes</ISINVOICE>
	<MFGJOURNAL>No</MFGJOURNAL>
	<HASDISCOUNTS>No</HASDISCOUNTS>
	<ASPAYSLIP>No</ASPAYSLIP>
	<ISCOSTCENTRE>No</ISCOSTCENTRE>
	<ISSTXNONREALIZEDVCH>No</ISSTXNONREALIZEDVCH>
	<ISEXCISEMANUFACTURERON>No</ISEXCISEMANUFACTURERON>
	<ISBLANKCHEQUE>No</ISBLANKCHEQUE>
	<ISVOID>No</ISVOID>
	<ISONHOLD>No</ISONHOLD>
	<ORDERLINESTATUS>No</ORDERLINESTATUS>
	<VATISAGNSTCANCSALES>No</VATISAGNSTCANCSALES>
	<VATISPURCEXEMPTED>No</VATISPURCEXEMPTED>
	<ISVATRESTAXINVOICE>No</ISVATRESTAXINVOICE>
	<VATISASSESABLECALCVCH>No</VATISASSESABLECALCVCH>
	<ISVATDUTYPAID>Yes</ISVATDUTYPAID>
	<ISDELIVERYSAMEASCONSIGNEE>No</ISDELIVERYSAMEASCONSIGNEE>
	<ISDISPATCHSAMEASCONSIGNOR>No</ISDISPATCHSAMEASCONSIGNOR>
	<ISDELETED>No</ISDELETED>
	<CHANGEVCHMODE>No</CHANGEVCHMODE>
	<ALTERID> 3</ALTERID>
	<MASTERID> 3</MASTERID>
	<VOUCHERKEY>187458142601240</VOUCHERKEY>
	<EXCLUDEDTAXATIONS.LIST>      </EXCLUDEDTAXATIONS.LIST>
	<OLDAUDITENTRIES.LIST>      </OLDAUDITENTRIES.LIST>
	<ACCOUNTAUDITENTRIES.LIST>      </ACCOUNTAUDITENTRIES.LIST>
	<AUDITENTRIES.LIST>      </AUDITENTRIES.LIST>
	<DUTYHEADDETAILS.LIST>      </DUTYHEADDETAILS.LIST>
	<SUPPLEMENTARYDUTYHEADDETAILS.LIST>      </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
	<EWAYBILLDETAILS.LIST>      </EWAYBILLDETAILS.LIST>
	<INVOICEDELNOTES.LIST>      </INVOICEDELNOTES.LIST>
	<INVOICEORDERLIST.LIST>      </INVOICEORDERLIST.LIST>
	<INVOICEINDENTLIST.LIST>      </INVOICEINDENTLIST.LIST>
	<ATTENDANCEENTRIES.LIST>      </ATTENDANCEENTRIES.LIST>
	<ORIGINVOICEDETAILS.LIST>      </ORIGINVOICEDETAILS.LIST>
	<INVOICEEXPORTLIST.LIST>      </INVOICEEXPORTLIST.LIST>
	<LEDGERENTRIES.LIST>
	<OLDAUDITENTRYIDS.LIST TYPE="Number">
	<OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
	</OLDAUDITENTRYIDS.LIST>
	<LEDGERNAME>Piyush Rai</LEDGERNAME>
	<GSTCLASS/>
	<ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
	<LEDGERFROMITEM>No</LEDGERFROMITEM>
	<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
	<ISPARTYLEDGER>Yes</ISPARTYLEDGER>
	<ISLASTDEEMEDPOSITIVE>Yes</ISLASTDEEMEDPOSITIVE>
	<ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
	<ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
	<AMOUNT>-15000.00</AMOUNT>
	<SERVICETAXDETAILS.LIST>       </SERVICETAXDETAILS.LIST>
	<BANKALLOCATIONS.LIST>       </BANKALLOCATIONS.LIST>
	<BILLALLOCATIONS.LIST>       </BILLALLOCATIONS.LIST>
	<INTERESTCOLLECTION.LIST>       </INTERESTCOLLECTION.LIST>
	<OLDAUDITENTRIES.LIST>       </OLDAUDITENTRIES.LIST>
	<ACCOUNTAUDITENTRIES.LIST>       </ACCOUNTAUDITENTRIES.LIST>
	<AUDITENTRIES.LIST>       </AUDITENTRIES.LIST>
	<INPUTCRALLOCS.LIST>       </INPUTCRALLOCS.LIST>
	<DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
	<EXCISEDUTYHEADDETAILS.LIST>       </EXCISEDUTYHEADDETAILS.LIST>
	<RATEDETAILS.LIST>       </RATEDETAILS.LIST>
	<SUMMARYALLOCS.LIST>       </SUMMARYALLOCS.LIST>
	<STPYMTDETAILS.LIST>       </STPYMTDETAILS.LIST>
	<EXCISEPAYMENTALLOCATIONS.LIST>       </EXCISEPAYMENTALLOCATIONS.LIST>
	<TAXBILLALLOCATIONS.LIST>       </TAXBILLALLOCATIONS.LIST>
	<TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
	<TDSEXPENSEALLOCATIONS.LIST>       </TDSEXPENSEALLOCATIONS.LIST>
	<VATSTATUTORYDETAILS.LIST>       </VATSTATUTORYDETAILS.LIST>
	<COSTTRACKALLOCATIONS.LIST>       </COSTTRACKALLOCATIONS.LIST>
	<REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
	<INVOICEWISEDETAILS.LIST>       </INVOICEWISEDETAILS.LIST>
	<VATITCDETAILS.LIST>       </VATITCDETAILS.LIST>
	<ADVANCETAXDETAILS.LIST>       </ADVANCETAXDETAILS.LIST>
	</LEDGERENTRIES.LIST>
	<ALLINVENTORYENTRIES.LIST>
	<STOCKITEMNAME>DAP</STOCKITEMNAME>
	<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
	<ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
	<ISAUTONEGATE>No</ISAUTONEGATE>
	<ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
	<ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
	<ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
	<ISPRIMARYITEM>No</ISPRIMARYITEM>
	<ISSCRAP>No</ISSCRAP>
	<RATE>100.00/Bag</RATE>
	<AMOUNT>5000.00</AMOUNT>
	<ACTUALQTY> 50 Bag</ACTUALQTY>
	<BILLEDQTY> 50 Bag</BILLEDQTY>
	<BATCHALLOCATIONS.LIST>
	<GODOWNNAME>Main Location</GODOWNNAME>
	<BATCHNAME>Primary Batch</BATCHNAME>
	<INDENTNO/>
	<ORDERNO/>
	<TRACKINGNUMBER/>



	<DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
	<AMOUNT>5000.00</AMOUNT>
	<ACTUALQTY> 50 Bag</ACTUALQTY>
	<BILLEDQTY> 50 Bag</BILLEDQTY>
	<ADDITIONALDETAILS.LIST>        </ADDITIONALDETAILS.LIST>
	<VOUCHERCOMPONENTLIST.LIST>        </VOUCHERCOMPONENTLIST.LIST>
	</BATCHALLOCATIONS.LIST>
	<ACCOUNTINGALLOCATIONS.LIST>
	<OLDAUDITENTRYIDS.LIST TYPE="Number">
	<OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
	</OLDAUDITENTRYIDS.LIST>
	<LEDGERNAME>Dap11</LEDGERNAME>
	<GSTCLASS/>
	<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
	<LEDGERFROMITEM>No</LEDGERFROMITEM>
	<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
	<ISPARTYLEDGER>No</ISPARTYLEDGER>
	<ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
	<ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
	<ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
	<AMOUNT>5000.00</AMOUNT>
	<SERVICETAXDETAILS.LIST>        </SERVICETAXDETAILS.LIST>
	<BANKALLOCATIONS.LIST>        </BANKALLOCATIONS.LIST>
	<BILLALLOCATIONS.LIST>        </BILLALLOCATIONS.LIST>
	<INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
	<OLDAUDITENTRIES.LIST>        </OLDAUDITENTRIES.LIST>
	<ACCOUNTAUDITENTRIES.LIST>        </ACCOUNTAUDITENTRIES.LIST>
	<AUDITENTRIES.LIST>        </AUDITENTRIES.LIST>
	<INPUTCRALLOCS.LIST>        </INPUTCRALLOCS.LIST>
	<DUTYHEADDETAILS.LIST>        </DUTYHEADDETAILS.LIST>
	<EXCISEDUTYHEADDETAILS.LIST>        </EXCISEDUTYHEADDETAILS.LIST>
	<RATEDETAILS.LIST>        </RATEDETAILS.LIST>
	<SUMMARYALLOCS.LIST>        </SUMMARYALLOCS.LIST>
	<STPYMTDETAILS.LIST>        </STPYMTDETAILS.LIST>
	<EXCISEPAYMENTALLOCATIONS.LIST>        </EXCISEPAYMENTALLOCATIONS.LIST>
	<TAXBILLALLOCATIONS.LIST>        </TAXBILLALLOCATIONS.LIST>
	<TAXOBJECTALLOCATIONS.LIST>        </TAXOBJECTALLOCATIONS.LIST>
	<TDSEXPENSEALLOCATIONS.LIST>        </TDSEXPENSEALLOCATIONS.LIST>
	<VATSTATUTORYDETAILS.LIST>        </VATSTATUTORYDETAILS.LIST>
	<COSTTRACKALLOCATIONS.LIST>        </COSTTRACKALLOCATIONS.LIST>
	<REFVOUCHERDETAILS.LIST>        </REFVOUCHERDETAILS.LIST>
	<INVOICEWISEDETAILS.LIST>        </INVOICEWISEDETAILS.LIST>
	<VATITCDETAILS.LIST>        </VATITCDETAILS.LIST>
	<ADVANCETAXDETAILS.LIST>        </ADVANCETAXDETAILS.LIST>
	</ACCOUNTINGALLOCATIONS.LIST>
	<DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
	<SUPPLEMENTARYDUTYHEADDETAILS.LIST>       </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
	<TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
	<REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
	<EXCISEALLOCATIONS.LIST>       </EXCISEALLOCATIONS.LIST>
	<EXPENSEALLOCATIONS.LIST>       </EXPENSEALLOCATIONS.LIST>
	</ALLINVENTORYENTRIES.LIST>
	<ALLINVENTORYENTRIES.LIST>
	<STOCKITEMNAME>DAP</STOCKITEMNAME>
	<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
	<ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
	<ISAUTONEGATE>No</ISAUTONEGATE>
	<ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
	<ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
	<ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
	<ISPRIMARYITEM>No</ISPRIMARYITEM>
	<ISSCRAP>No</ISSCRAP>
	<RATE>100.00/Bag</RATE>
	<AMOUNT>5000.00</AMOUNT>
	<ACTUALQTY> 50 Bag</ACTUALQTY>
	<BILLEDQTY> 50 Bag</BILLEDQTY>
	<BATCHALLOCATIONS.LIST>
	<GODOWNNAME>Main Location</GODOWNNAME>
	<BATCHNAME>Primary Batch</BATCHNAME>
	<INDENTNO/>
	<ORDERNO/>
	<TRACKINGNUMBER/>


	<DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
	<AMOUNT>5000.00</AMOUNT>
	<ACTUALQTY> 50 Bag</ACTUALQTY>
	<BILLEDQTY> 50 Bag</BILLEDQTY>
	<ADDITIONALDETAILS.LIST>        </ADDITIONALDETAILS.LIST>
	<VOUCHERCOMPONENTLIST.LIST>        </VOUCHERCOMPONENTLIST.LIST>
	</BATCHALLOCATIONS.LIST>
	<ACCOUNTINGALLOCATIONS.LIST>
	<OLDAUDITENTRYIDS.LIST TYPE="Number">
	<OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
	</OLDAUDITENTRYIDS.LIST>
	<LEDGERNAME>Dap11</LEDGERNAME>
	<GSTCLASS/>
	<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
	<LEDGERFROMITEM>No</LEDGERFROMITEM>
	<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
	<ISPARTYLEDGER>No</ISPARTYLEDGER>
	<ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
	<ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
	<ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
	<AMOUNT>5000.00</AMOUNT>
	<SERVICETAXDETAILS.LIST>        </SERVICETAXDETAILS.LIST>
	<BANKALLOCATIONS.LIST>        </BANKALLOCATIONS.LIST>
	<BILLALLOCATIONS.LIST>        </BILLALLOCATIONS.LIST>
	<INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
	<OLDAUDITENTRIES.LIST>        </OLDAUDITENTRIES.LIST>
	<ACCOUNTAUDITENTRIES.LIST>        </ACCOUNTAUDITENTRIES.LIST>
	<AUDITENTRIES.LIST>        </AUDITENTRIES.LIST>
	<INPUTCRALLOCS.LIST>        </INPUTCRALLOCS.LIST>
	<DUTYHEADDETAILS.LIST>        </DUTYHEADDETAILS.LIST>
	<EXCISEDUTYHEADDETAILS.LIST>        </EXCISEDUTYHEADDETAILS.LIST>
	<RATEDETAILS.LIST>        </RATEDETAILS.LIST>
	<SUMMARYALLOCS.LIST>        </SUMMARYALLOCS.LIST>
	<STPYMTDETAILS.LIST>        </STPYMTDETAILS.LIST>
	<EXCISEPAYMENTALLOCATIONS.LIST>        </EXCISEPAYMENTALLOCATIONS.LIST>
	<TAXBILLALLOCATIONS.LIST>        </TAXBILLALLOCATIONS.LIST>
	<TAXOBJECTALLOCATIONS.LIST>        </TAXOBJECTALLOCATIONS.LIST>
	<TDSEXPENSEALLOCATIONS.LIST>        </TDSEXPENSEALLOCATIONS.LIST>
	<VATSTATUTORYDETAILS.LIST>        </VATSTATUTORYDETAILS.LIST>
	<COSTTRACKALLOCATIONS.LIST>        </COSTTRACKALLOCATIONS.LIST>
	<REFVOUCHERDETAILS.LIST>        </REFVOUCHERDETAILS.LIST>
	<INVOICEWISEDETAILS.LIST>        </INVOICEWISEDETAILS.LIST>
	<VATITCDETAILS.LIST>        </VATITCDETAILS.LIST>
	<ADVANCETAXDETAILS.LIST>        </ADVANCETAXDETAILS.LIST>
	</ACCOUNTINGALLOCATIONS.LIST>
	<DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
	<SUPPLEMENTARYDUTYHEADDETAILS.LIST>       </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
	<TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
	<REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
	<EXCISEALLOCATIONS.LIST>       </EXCISEALLOCATIONS.LIST>
	<EXPENSEALLOCATIONS.LIST>       </EXPENSEALLOCATIONS.LIST>
	</ALLINVENTORYENTRIES.LIST>
	<ALLINVENTORYENTRIES.LIST>
	<STOCKITEMNAME>DAP</STOCKITEMNAME>
	<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
	<ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
	<ISAUTONEGATE>No</ISAUTONEGATE>
	<ISCUSTOMSCLEARANCE>No</ISCUSTOMSCLEARANCE>
	<ISTRACKCOMPONENT>No</ISTRACKCOMPONENT>
	<ISTRACKPRODUCTION>No</ISTRACKPRODUCTION>
	<ISPRIMARYITEM>No</ISPRIMARYITEM>
	<ISSCRAP>No</ISSCRAP>
	<RATE>100.00/Bag</RATE>
	<AMOUNT>5000.00</AMOUNT>
	<ACTUALQTY> 50 Bag</ACTUALQTY>
	<BILLEDQTY> 50 Bag</BILLEDQTY>
	<BATCHALLOCATIONS.LIST>
	<GODOWNNAME>Main Location</GODOWNNAME>
	<BATCHNAME>Primary Batch</BATCHNAME>
	<INDENTNO/>
	<ORDERNO/>
	<TRACKINGNUMBER/>

	<DYNAMICCSTISCLEARED>No</DYNAMICCSTISCLEARED>
	<AMOUNT>5000.00</AMOUNT>
	<ACTUALQTY> 50 Bag</ACTUALQTY>
	<BILLEDQTY> 50 Bag</BILLEDQTY>
	<ADDITIONALDETAILS.LIST>        </ADDITIONALDETAILS.LIST>
	<VOUCHERCOMPONENTLIST.LIST>        </VOUCHERCOMPONENTLIST.LIST>
	</BATCHALLOCATIONS.LIST>
	<ACCOUNTINGALLOCATIONS.LIST>
	<OLDAUDITENTRYIDS.LIST TYPE="Number">
	<OLDAUDITENTRYIDS>-1</OLDAUDITENTRYIDS>
	</OLDAUDITENTRYIDS.LIST>
	<LEDGERNAME>Dap11</LEDGERNAME>
	<GSTCLASS/>
	<ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
	<LEDGERFROMITEM>No</LEDGERFROMITEM>
	<REMOVEZEROENTRIES>No</REMOVEZEROENTRIES>
	<ISPARTYLEDGER>No</ISPARTYLEDGER>
	<ISLASTDEEMEDPOSITIVE>No</ISLASTDEEMEDPOSITIVE>
	<ISCAPVATTAXALTERED>No</ISCAPVATTAXALTERED>
	<ISCAPVATNOTCLAIMED>No</ISCAPVATNOTCLAIMED>
	<AMOUNT>5000.00</AMOUNT>
	<SERVICETAXDETAILS.LIST>        </SERVICETAXDETAILS.LIST>
	<BANKALLOCATIONS.LIST>        </BANKALLOCATIONS.LIST>
	<BILLALLOCATIONS.LIST>        </BILLALLOCATIONS.LIST>
	<INTERESTCOLLECTION.LIST>        </INTERESTCOLLECTION.LIST>
	<OLDAUDITENTRIES.LIST>        </OLDAUDITENTRIES.LIST>
	<ACCOUNTAUDITENTRIES.LIST>        </ACCOUNTAUDITENTRIES.LIST>
	<AUDITENTRIES.LIST>        </AUDITENTRIES.LIST>
	<INPUTCRALLOCS.LIST>        </INPUTCRALLOCS.LIST>
	<DUTYHEADDETAILS.LIST>        </DUTYHEADDETAILS.LIST>
	<EXCISEDUTYHEADDETAILS.LIST>        </EXCISEDUTYHEADDETAILS.LIST>
	<RATEDETAILS.LIST>        </RATEDETAILS.LIST>
	<SUMMARYALLOCS.LIST>        </SUMMARYALLOCS.LIST>
	<STPYMTDETAILS.LIST>        </STPYMTDETAILS.LIST>
	<EXCISEPAYMENTALLOCATIONS.LIST>        </EXCISEPAYMENTALLOCATIONS.LIST>
	<TAXBILLALLOCATIONS.LIST>        </TAXBILLALLOCATIONS.LIST>
	<TAXOBJECTALLOCATIONS.LIST>        </TAXOBJECTALLOCATIONS.LIST>
	<TDSEXPENSEALLOCATIONS.LIST>        </TDSEXPENSEALLOCATIONS.LIST>
	<VATSTATUTORYDETAILS.LIST>        </VATSTATUTORYDETAILS.LIST>
	<COSTTRACKALLOCATIONS.LIST>        </COSTTRACKALLOCATIONS.LIST>
	<REFVOUCHERDETAILS.LIST>        </REFVOUCHERDETAILS.LIST>
	<INVOICEWISEDETAILS.LIST>        </INVOICEWISEDETAILS.LIST>
	<VATITCDETAILS.LIST>        </VATITCDETAILS.LIST>
	<ADVANCETAXDETAILS.LIST>        </ADVANCETAXDETAILS.LIST>
	</ACCOUNTINGALLOCATIONS.LIST>
	<DUTYHEADDETAILS.LIST>       </DUTYHEADDETAILS.LIST>
	<SUPPLEMENTARYDUTYHEADDETAILS.LIST>       </SUPPLEMENTARYDUTYHEADDETAILS.LIST>
	<TAXOBJECTALLOCATIONS.LIST>       </TAXOBJECTALLOCATIONS.LIST>
	<REFVOUCHERDETAILS.LIST>       </REFVOUCHERDETAILS.LIST>
	<EXCISEALLOCATIONS.LIST>       </EXCISEALLOCATIONS.LIST>
	<EXPENSEALLOCATIONS.LIST>       </EXPENSEALLOCATIONS.LIST>
	</ALLINVENTORYENTRIES.LIST>
	<PAYROLLMODEOFPAYMENT.LIST>      </PAYROLLMODEOFPAYMENT.LIST>
	<ATTDRECORDS.LIST>      </ATTDRECORDS.LIST>
	<GSTEWAYCONSIGNORADDRESS.LIST>      </GSTEWAYCONSIGNORADDRESS.LIST>
	<GSTEWAYCONSIGNEEADDRESS.LIST>      </GSTEWAYCONSIGNEEADDRESS.LIST>
	<TEMPGSTRATEDETAILS.LIST>      </TEMPGSTRATEDETAILS.LIST>
	</VOUCHER>
	</TALLYMESSAGE>
	<TALLYMESSAGE xmlns:UDF="TallyUDF">
	<COMPANY>
	<REMOTECMPINFO.LIST MERGE="Yes">
	<NAME>17a2ccb3-0887-4e42-ab7c-605e77d5e33e</NAME>
	<REMOTECMPNAME>Logimetrix Techsolutions Private Limited</REMOTECMPNAME>
	<REMOTECMPSTATE>Uttar Pradesh</REMOTECMPSTATE>
	</REMOTECMPINFO.LIST>
	</COMPANY>
	</TALLYMESSAGE>
	<TALLYMESSAGE xmlns:UDF="TallyUDF">
	<COMPANY>
	<REMOTECMPINFO.LIST MERGE="Yes">
	<NAME>17a2ccb3-0887-4e42-ab7c-605e77d5e33e</NAME>
	<REMOTECMPNAME>Logimetrix Techsolutions Private Limited</REMOTECMPNAME>
	<REMOTECMPSTATE>Uttar Pradesh</REMOTECMPSTATE>
	</REMOTECMPINFO.LIST>
	</COMPANY>
	</TALLYMESSAGE>
	</REQUESTDATA>
	</IMPORTDATA>
	</BODY>
	</ENVELOPE>
	';

	/* Actual code for importing goes here */
	$server = 'localhost:9999';
	$headers = array( "Content-type: text/xml" ,"Content-length: ".strlen($requestXML) ,"Connection: close" );

	$ch = curl_init();
	curl_setopt($ch, CURLOPT_URL, $server);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_TIMEOUT, 100);
	curl_setopt($ch, CURLOPT_POST, true);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $requestXML);
	curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
	$data = curl_exec($ch);

	if(curl_errno($ch)){
		print curl_error($ch);
		echo "  something went wrong..... try later";
	}else{
		echo " request accepted";
		print $data;
		curl_close($ch);
	}
}

?>